### ISSUE TITLE
No Domains available !!!

### ISSUE THREAD

**Issue by Gab-182** [Aztaro97/RNS-Dapp#5]
No Domains available !!!
<img width="997" alt="Screenshot 2024-02-21 at 5 19 29 PM" src="https://github.com/Aztaro97/rns-app/assets/83855149/47353476-a5e6-48bd-8639-0b76d2127945">

**Comment by Aztaro97** [comment]
Thank you @Gab-182 for your feedback, 
the project is currently on hold, looking for more collab in the feature
